# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form_sanche_new.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1073, 652)
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setGeometry(QtCore.QRect(550, 30, 511, 101))
        self.tabWidget.setObjectName("tabWidget")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.tab_2)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(0, 0, 501, 65))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.x1_min_edit = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.x1_min_edit.setObjectName("x1_min_edit")
        self.horizontalLayout_2.addWidget(self.x1_min_edit)
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.x1_max_edit = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.x1_max_edit.setObjectName("x1_max_edit")
        self.horizontalLayout_2.addWidget(self.x1_max_edit)
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.label_5)
        self.x2_min_edit = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.x2_min_edit.setObjectName("x2_min_edit")
        self.horizontalLayout_2.addWidget(self.x2_min_edit)
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_2.addWidget(self.label_6)
        self.x2_max_edit = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.x2_max_edit.setObjectName("x2_max_edit")
        self.horizontalLayout_2.addWidget(self.x2_max_edit)
        self.label_7 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_2.addWidget(self.label_7)
        self.step_combBox = QtWidgets.QComboBox(self.verticalLayoutWidget_2)
        self.step_combBox.setObjectName("step_combBox")
        self.step_combBox.addItem("")
        self.step_combBox.addItem("")
        self.step_combBox.addItem("")
        self.step_combBox.addItem("")
        self.horizontalLayout_2.addWidget(self.step_combBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.tabWidget.addTab(self.tab_2, "")
        self.result_table = QtWidgets.QTableWidget(Form)
        self.result_table.setGeometry(QtCore.QRect(0, 340, 621, 261))
        self.result_table.setRowCount(12)
        self.result_table.setColumnCount(12)
        self.result_table.setObjectName("result_table")
        self.result_table.horizontalHeader().setVisible(False)
        self.result_table.horizontalHeader().setDefaultSectionSize(50)
        self.result_table.horizontalHeader().setHighlightSections(False)
        self.result_table.verticalHeader().setVisible(False)
        self.result_table.verticalHeader().setDefaultSectionSize(20)
        self.run_button = QtWidgets.QPushButton(Form)
        self.run_button.setGeometry(QtCore.QRect(630, 340, 181, 41))
        self.run_button.setObjectName("run_button")
        self.tabWidget_2 = QtWidgets.QTabWidget(Form)
        self.tabWidget_2.setGeometry(QtCore.QRect(5, 10, 511, 321))
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.exeption_table = QtWidgets.QTableWidget(self.tab_6)
        self.exeption_table.setGeometry(QtCore.QRect(10, 40, 491, 201))
        self.exeption_table.setRowCount(5)
        self.exeption_table.setColumnCount(1)
        self.exeption_table.setObjectName("exeption_table")
        item = QtWidgets.QTableWidgetItem()
        self.exeption_table.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.exeption_table.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.exeption_table.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.exeption_table.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.exeption_table.setItem(4, 0, item)
        self.exeption_table.horizontalHeader().setVisible(False)
        self.exeption_table.horizontalHeader().setStretchLastSection(True)
        self.exeption_table.verticalHeader().setVisible(False)
        self.exeption_table.verticalHeader().setDefaultSectionSize(30)
        self.label_8 = QtWidgets.QLabel(self.tab_6)
        self.label_8.setGeometry(QtCore.QRect(10, 10, 71, 17))
        self.label_8.setObjectName("label_8")
        self.objectiv_func_edit = QtWidgets.QLineEdit(self.tab_6)
        self.objectiv_func_edit.setGeometry(QtCore.QRect(79, 7, 301, 25))
        self.objectiv_func_edit.setObjectName("objectiv_func_edit")
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.tab_6)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(10, 240, 491, 41))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.exeption_left_edit = QtWidgets.QLineEdit(self.horizontalLayoutWidget_3)
        self.exeption_left_edit.setObjectName("exeption_left_edit")
        self.horizontalLayout_3.addWidget(self.exeption_left_edit)
        self.combBox = QtWidgets.QComboBox(self.horizontalLayoutWidget_3)
        self.combBox.setObjectName("combBox")
        self.combBox.addItem("")
        self.combBox.addItem("")
        self.combBox.addItem("")
        self.combBox.addItem("")
        self.combBox.addItem("")
        self.horizontalLayout_3.addWidget(self.combBox)
        self.exeption_right_edit = QtWidgets.QLineEdit(self.horizontalLayoutWidget_3)
        self.exeption_right_edit.setObjectName("exeption_right_edit")
        self.horizontalLayout_3.addWidget(self.exeption_right_edit)
        self.add_btn = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.add_btn.setObjectName("add_btn")
        self.horizontalLayout_3.addWidget(self.add_btn)
        self.tabWidget_2.addTab(self.tab_6, "")
        self.btn_graph = QtWidgets.QPushButton(Form)
        self.btn_graph.setGeometry(QtCore.QRect(940, 340, 121, 41))
        self.btn_graph.setInputMethodHints(QtCore.Qt.ImhNone)
        self.btn_graph.setAutoRepeat(False)
        self.btn_graph.setAutoExclusive(False)
        self.btn_graph.setObjectName("btn_graph")
        self.method_CombBox = QtWidgets.QComboBox(Form)
        self.method_CombBox.setGeometry(QtCore.QRect(550, 150, 431, 41))
        self.method_CombBox.setObjectName("method_CombBox")
        self.method_CombBox.addItem("")
        self.method_CombBox.addItem("")
        self.method_CombBox.addItem("")
        self.method_CombBox.addItem("")
        self.tabWidget_3 = QtWidgets.QTabWidget(Form)
        self.tabWidget_3.setGeometry(QtCore.QRect(550, 200, 511, 121))
        self.tabWidget_3.setObjectName("tabWidget_3")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label_10 = QtWidgets.QLabel(self.tab)
        self.label_10.setGeometry(QtCore.QRect(270, 44, 161, 17))
        self.label_10.setObjectName("label_10")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(150, 40, 21, 17))
        self.label_2.setObjectName("label_2")
        self.bottom_step_hyk_edit = QtWidgets.QLineEdit(self.tab)
        self.bottom_step_hyk_edit.setGeometry(QtCore.QRect(430, 44, 61, 25))
        self.bottom_step_hyk_edit.setObjectName("bottom_step_hyk_edit")
        self.step_hyk_edit = QtWidgets.QLineEdit(self.tab)
        self.step_hyk_edit.setGeometry(QtCore.QRect(430, 10, 61, 25))
        self.step_hyk_edit.setObjectName("step_hyk_edit")
        self.label_9 = QtWidgets.QLabel(self.tab)
        self.label_9.setGeometry(QtCore.QRect(395, 14, 31, 17))
        self.label_9.setObjectName("label_9")
        self.x1_hyk_edit = QtWidgets.QLineEdit(self.tab)
        self.x1_hyk_edit.setGeometry(QtCore.QRect(170, 10, 51, 25))
        self.x1_hyk_edit.setObjectName("x1_hyk_edit")
        self.x2_hyk_edit = QtWidgets.QLineEdit(self.tab)
        self.x2_hyk_edit.setGeometry(QtCore.QRect(170, 40, 51, 25))
        self.x2_hyk_edit.setObjectName("x2_hyk_edit")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(150, 10, 21, 17))
        self.label.setObjectName("label")
        self.tabWidget_3.addTab(self.tab, "")

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        self.step_combBox.setCurrentIndex(2)
        self.tabWidget_2.setCurrentIndex(0)
        self.combBox.setCurrentIndex(4)
        self.tabWidget_3.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "OPR"))
        self.label_4.setText(_translate("Form", "x1min"))
        self.x1_min_edit.setText(_translate("Form", "-1"))
        self.label_3.setText(_translate("Form", "max"))
        self.x1_max_edit.setText(_translate("Form", "4"))
        self.label_5.setText(_translate("Form", "x2min"))
        self.x2_min_edit.setText(_translate("Form", "-1"))
        self.label_6.setText(_translate("Form", "max"))
        self.x2_max_edit.setText(_translate("Form", "4"))
        self.label_7.setText(_translate("Form", "шаг"))
        self.step_combBox.setItemText(0, _translate("Form", "0.1"))
        self.step_combBox.setItemText(1, _translate("Form", "0.2"))
        self.step_combBox.setItemText(2, _translate("Form", "0.5"))
        self.step_combBox.setItemText(3, _translate("Form", "1"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Form", "Параметры сетки"))
        self.run_button.setText(_translate("Form", "Посчитать"))
        __sortingEnabled = self.exeption_table.isSortingEnabled()
        self.exeption_table.setSortingEnabled(False)
        item = self.exeption_table.item(0, 0)
        item.setText(_translate("Form", "2*x1 + 3*x2 >= 6"))
        item = self.exeption_table.item(1, 0)
        item.setText(_translate("Form", "x1 + 4*x2 >= 5"))
        item = self.exeption_table.item(2, 0)
        item.setText(_translate("Form", "x1 >= 0"))
        item = self.exeption_table.item(3, 0)
        item.setText(_translate("Form", "x2 >= 0"))
        self.exeption_table.setSortingEnabled(__sortingEnabled)
        self.label_8.setText(_translate("Form", "F(x1,x2) ="))
        self.objectiv_func_edit.setText(_translate("Form", "0.5 * x2**2 + 0.5*x1**2 - x1 - 2*x2 + 5"))
        self.combBox.setItemText(0, _translate("Form", "<="))
        self.combBox.setItemText(1, _translate("Form", "<"))
        self.combBox.setItemText(2, _translate("Form", "="))
        self.combBox.setItemText(3, _translate("Form", ">"))
        self.combBox.setItemText(4, _translate("Form", ">="))
        self.add_btn.setText(_translate("Form", "Add"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_6), _translate("Form", "Исключения"))
        self.btn_graph.setText(_translate("Form", "Линии уровня"))
        self.method_CombBox.setItemText(0, _translate("Form", "Метод прямого перебора по сетке"))
        self.method_CombBox.setItemText(1, _translate("Form", "Метод Монте-Карло"))
        self.method_CombBox.setItemText(2, _translate("Form", "Метод Хука-Дживса"))
        self.method_CombBox.setItemText(3, _translate("Form", "Метод штрафных функций"))
        self.label_10.setText(_translate("Form", "нижняя граница шага"))
        self.label_2.setText(_translate("Form", "х2"))
        self.label_9.setText(_translate("Form", "шаг"))
        self.label.setText(_translate("Form", "x1 "))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab), _translate("Form", "Парам. нач. точки (для 3 и 4 методов)"))

