# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'finish_form_OPR.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1141, 440)
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setGeometry(QtCore.QRect(4, 330, 511, 101))
        self.tabWidget.setObjectName("tabWidget")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.tab_2)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(0, 0, 501, 65))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.x1_min_edit = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.x1_min_edit.setObjectName("x1_min_edit")
        self.horizontalLayout_2.addWidget(self.x1_min_edit)
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.x1_max_edit = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.x1_max_edit.setObjectName("x1_max_edit")
        self.horizontalLayout_2.addWidget(self.x1_max_edit)
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.label_5)
        self.x2_min_edit = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.x2_min_edit.setObjectName("x2_min_edit")
        self.horizontalLayout_2.addWidget(self.x2_min_edit)
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_2.addWidget(self.label_6)
        self.x2_max_edit = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.x2_max_edit.setObjectName("x2_max_edit")
        self.horizontalLayout_2.addWidget(self.x2_max_edit)
        self.label_7 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_2.addWidget(self.label_7)
        self.step_combBox = QtWidgets.QComboBox(self.verticalLayoutWidget_2)
        self.step_combBox.setObjectName("step_combBox")
        self.step_combBox.addItem("")
        self.step_combBox.addItem("")
        self.step_combBox.addItem("")
        self.step_combBox.addItem("")
        self.horizontalLayout_2.addWidget(self.step_combBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.method_CombBox = QtWidgets.QComboBox(self.tab_3)
        self.method_CombBox.setGeometry(QtCore.QRect(50, 10, 431, 41))
        self.method_CombBox.setObjectName("method_CombBox")
        self.method_CombBox.addItem("")
        self.method_CombBox.addItem("")
        self.method_CombBox.addItem("")
        self.method_CombBox.addItem("")
        self.tabWidget.addTab(self.tab_3, "")
        self.result_table = QtWidgets.QTableWidget(Form)
        self.result_table.setGeometry(QtCore.QRect(525, 40, 602, 242))
        self.result_table.setRowCount(12)
        self.result_table.setColumnCount(12)
        self.result_table.setObjectName("result_table")
        self.result_table.horizontalHeader().setVisible(False)
        self.result_table.horizontalHeader().setDefaultSectionSize(50)
        self.result_table.horizontalHeader().setHighlightSections(False)
        self.result_table.verticalHeader().setVisible(False)
        self.result_table.verticalHeader().setDefaultSectionSize(20)
        self.label_9 = QtWidgets.QLabel(Form)
        self.label_9.setGeometry(QtCore.QRect(520, 20, 81, 17))
        self.label_9.setObjectName("label_9")
        self.min_label = QtWidgets.QLabel(Form)
        self.min_label.setGeometry(QtCore.QRect(620, 20, 161, 17))
        self.min_label.setText("")
        self.min_label.setObjectName("min_label")
        self.run_button = QtWidgets.QPushButton(Form)
        self.run_button.setGeometry(QtCore.QRect(625, 390, 89, 25))
        self.run_button.setObjectName("run_button")
        self.tabWidget_2 = QtWidgets.QTabWidget(Form)
        self.tabWidget_2.setGeometry(QtCore.QRect(5, 10, 511, 311))
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.exeption_table = QtWidgets.QTableWidget(self.tab_6)
        self.exeption_table.setGeometry(QtCore.QRect(10, 40, 491, 201))
        self.exeption_table.setRowCount(5)
        self.exeption_table.setColumnCount(1)
        self.exeption_table.setObjectName("exeption_table")
        item = QtWidgets.QTableWidgetItem()
        self.exeption_table.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.exeption_table.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.exeption_table.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.exeption_table.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.exeption_table.setItem(4, 0, item)
        self.exeption_table.horizontalHeader().setVisible(False)
        self.exeption_table.horizontalHeader().setStretchLastSection(True)
        self.exeption_table.verticalHeader().setVisible(False)
        self.exeption_table.verticalHeader().setDefaultSectionSize(30)
        self.label_8 = QtWidgets.QLabel(self.tab_6)
        self.label_8.setGeometry(QtCore.QRect(10, 10, 181, 17))
        self.label_8.setObjectName("label_8")
        self.objectiv_func_edit = QtWidgets.QLineEdit(self.tab_6)
        self.objectiv_func_edit.setGeometry(QtCore.QRect(190, 10, 301, 25))
        self.objectiv_func_edit.setObjectName("objectiv_func_edit")
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.tab_6)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(10, 240, 491, 41))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.exeption_left_edit = QtWidgets.QLineEdit(self.horizontalLayoutWidget_3)
        self.exeption_left_edit.setObjectName("exeption_left_edit")
        self.horizontalLayout_3.addWidget(self.exeption_left_edit)
        self.combBox = QtWidgets.QComboBox(self.horizontalLayoutWidget_3)
        self.combBox.setObjectName("combBox")
        self.combBox.addItem("")
        self.combBox.addItem("")
        self.combBox.addItem("")
        self.combBox.addItem("")
        self.combBox.addItem("")
        self.horizontalLayout_3.addWidget(self.combBox)
        self.exeption_right_edit = QtWidgets.QLineEdit(self.horizontalLayoutWidget_3)
        self.exeption_right_edit.setObjectName("exeption_right_edit")
        self.horizontalLayout_3.addWidget(self.exeption_right_edit)
        self.add_btn = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.add_btn.setObjectName("add_btn")
        self.horizontalLayout_3.addWidget(self.add_btn)
        self.tabWidget_2.addTab(self.tab_6, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.tabWidget_2.addTab(self.tab_7, "")
        self.except_label = QtWidgets.QLabel(Form)
        self.except_label.setGeometry(QtCore.QRect(550, 330, 561, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.except_label.setFont(font)
        self.except_label.setText("")
        self.except_label.setAlignment(QtCore.Qt.AlignCenter)
        self.except_label.setObjectName("except_label")

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        self.step_combBox.setCurrentIndex(2)
        self.tabWidget_2.setCurrentIndex(0)
        self.combBox.setCurrentIndex(4)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "OPR"))
        self.label_2.setText(_translate("Form", "Solution area"))
        self.label_4.setText(_translate("Form", "x1min"))
        self.x1_min_edit.setText(_translate("Form", "-1"))
        self.label_3.setText(_translate("Form", "max"))
        self.x1_max_edit.setText(_translate("Form", "4"))
        self.label_5.setText(_translate("Form", "x2min"))
        self.x2_min_edit.setText(_translate("Form", "-1"))
        self.label_6.setText(_translate("Form", "max"))
        self.x2_max_edit.setText(_translate("Form", "4"))
        self.label_7.setText(_translate("Form", "step"))
        self.step_combBox.setItemText(0, _translate("Form", "0.1"))
        self.step_combBox.setItemText(1, _translate("Form", "0.2"))
        self.step_combBox.setItemText(2, _translate("Form", "0.5"))
        self.step_combBox.setItemText(3, _translate("Form", "1"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Form", "Area"))
        self.method_CombBox.setItemText(0, _translate("Form", "Метод прямого перебора по сетке"))
        self.method_CombBox.setItemText(1, _translate("Form", "Метод Монте-Карло"))
        self.method_CombBox.setItemText(2, _translate("Form", "Метод Хука-Дживса"))
        self.method_CombBox.setItemText(3, _translate("Form", "Метод штрафных функций"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Form", "Method"))
        self.label_9.setText(_translate("Form", "minF(x1,x2)"))
        self.run_button.setText(_translate("Form", "Run"))
        __sortingEnabled = self.exeption_table.isSortingEnabled()
        self.exeption_table.setSortingEnabled(False)
        item = self.exeption_table.item(0, 0)
        item.setText(_translate("Form", "2*x1 - 3*x2 - 3 >= 0"))
        item = self.exeption_table.item(1, 0)
        item.setText(_translate("Form", "x1 + x2 - 3 >= 0"))
        item = self.exeption_table.item(2, 0)
        item.setText(_translate("Form", "2*x1 - x2 - 4 >= 0"))
        item = self.exeption_table.item(3, 0)
        item.setText(_translate("Form", "x1 >= 0"))
        item = self.exeption_table.item(4, 0)
        item.setText(_translate("Form", "x2 >= 0"))
        self.exeption_table.setSortingEnabled(__sortingEnabled)
        self.label_8.setText(_translate("Form", "Objectiv function F(x1,x2)"))
        self.objectiv_func_edit.setText(_translate("Form", "x1 ** 2 + x2 ** 2 - 2.4 * x1 - 5.6 * x2"))
        self.combBox.setItemText(0, _translate("Form", "<="))
        self.combBox.setItemText(1, _translate("Form", "<"))
        self.combBox.setItemText(2, _translate("Form", "="))
        self.combBox.setItemText(3, _translate("Form", ">"))
        self.combBox.setItemText(4, _translate("Form", ">="))
        self.add_btn.setText(_translate("Form", "Add"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_6), _translate("Form", "Exeptions"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_7), _translate("Form", "Graphic"))

